apiVersion: v1
kind: Namespace
metadata:
  name: llama-stack-operator-system
  labels:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/name: llama-stack-operator
    control-plane: controller-manager
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/name: llama-stack-operator
  name: llama-stack-operator-controller-manager
  namespace: llama-stack-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/name: llama-stack-operator
  name: llama-stack-operator-leader-election-role
  namespace: llama-stack-operator-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/name: llama-stack-operator
  name: llama-stack-operator-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - deployments
  - persistentvolumeclaims
  - persistentvolumes
  - pods
  - pods/exec
  - pods/log
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - services/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/finalizers
  verbs:
  - '*'
- apiGroups:
  - llamastack.io
  resources:
  - llamastackdistributions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - llamastack.io
  resources:
  - llamastackdistributions/finalizers
  verbs:
  - update
- apiGroups:
  - llamastack.io
  resources:
  - llamastackdistributions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/name: llama-stack-operator
  name: llama-stack-operator-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/name: llama-stack-operator
  name: llama-stack-operator-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/name: llama-stack-operator
  name: llama-stack-operator-leader-election-rolebinding
  namespace: llama-stack-operator-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: llama-stack-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: llama-stack-operator-controller-manager
  namespace: llama-stack-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/name: llama-stack-operator
  name: llama-stack-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: llama-stack-operator-manager-role
subjects:
- kind: ServiceAccount
  name: llama-stack-operator-controller-manager
  namespace: llama-stack-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/name: llama-stack-operator
  name: llama-stack-operator-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: llama-stack-operator-proxy-role
subjects:
- kind: ServiceAccount
  name: llama-stack-operator-controller-manager
  namespace: llama-stack-operator-system
---
apiVersion: v1
data:
  OLLAMA_IMAGE: docker.io/llamastack/distribution-ollama:latest
  VLLM_IMAGE: docker.io/llamastack/distribution-remote-vllm:latest
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/name: llama-stack-operator
  name: llama-stack-operator-lls-parameters-544mdk2b4h
  namespace: llama-stack-operator-system
---
apiVersion: v1
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: 54e06e98.llamastack.io
    # leaderElectionReleaseOnCancel defines if the leader should step down volume
    # when the Manager ends. This requires the binary to immediately end when the
    # Manager is stopped, otherwise, this setting is unsafe. Setting this significantly
    # speeds up voluntary leader transitions as the new leader don't have to wait
    # LeaseDuration time first.
    # In the default scaffold provided, the program ends immediately after
    # the manager stops, so would be fine to enable this option. However,
    # if you are doing or is intended to do any operation such as perform cleanups
    # after the manager stops then its usage might be unsafe.
    # leaderElectionReleaseOnCancel: true
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/name: llama-stack-operator
  name: llama-stack-operator-manager-config
  namespace: llama-stack-operator-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/name: llama-stack-operator
    control-plane: controller-manager
  name: llama-stack-operator-controller-manager-metrics-service
  namespace: llama-stack-operator-system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/name: llama-stack-operator
    control-plane: controller-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/name: llama-stack-operator
    control-plane: controller-manager
  name: llama-stack-operator-controller-manager
  namespace: llama-stack-operator-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: controller-manager
      app.kubernetes.io/name: llama-stack-operator
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/component: controller-manager
        app.kubernetes.io/name: llama-stack-operator
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --leader-elect
        command:
        - /manager
        env:
        - name: OLLAMA_IMAGE
          value: docker.io/llamastack/distribution-ollama:latest
        - name: VLLM_IMAGE
          value: docker.io/llamastack/distribution-remote-vllm:latest
        image: quay.io/llamastack/llama-stack-operator:latest
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsNonRoot: true
      serviceAccountName: llama-stack-operator-controller-manager
      terminationGracePeriodSeconds: 10


