---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  finalizers:
  - odh.inferenceservice.finalizers
  - inferenceservice.finalizers
  name: vllm
labels:
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      args:
      - "--dtype=half"
      - "--max-model-len=20000"
      - "--gpu-memory-utilization=0.95"
      - "--enable-chunked-prefill"
      - "--enable-auto-tool-choice"
      - "--tool-call-parser=llama3_json"
      - "--chat-template=/app/data/template/tool_chat_template_llama3.2_json.jinja"
      modelFormat:
        name: vLLM
      name: ''
      resources:
        limits:
          cpu: '1'
          memory: 10Gi
          nvidia.com/gpu: '1'
        requests:
          cpu: '1'
          memory: 10Gi
          nvidia.com/gpu: '1'
      runtime: vllm
      storageUri: oci://quay.io/redhat-ai-services/modelcar-catalog:llama-3.2-3b-instruct
    tolerations:
    - effect: NoSchedule
      key: nvidia.com/gpu
      operator: Exists
